[project]
name = "src"
version = "0.0.1"
description = "Adversial Multimodel Recommendation Engine"
authors = [{name = "Ankur Kumar", email = "kumarankur0006@gmail.com"}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}